<Project>
    <PropertyGroup>
        <GodotPath>/home/phil/Data/StS2-Modding/megadot-4.5.1-m.14-linux-x86_64-editor-csharp/MegaDot_v4.5.1-stable_mono_linux.x86_64</GodotPath>
        <Sts2Path>/home/phil/Steam/SteamLibrary/steamapps/common/Slay the Spire 2</Sts2Path>
    </PropertyGroup>
</Project>
