using BaseLib.Abstracts;
using BaseLib.Utils;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models.CardPools;
using MegaCrit.Sts2.Core.Models.Powers;

namespace BalancedVarietyPack.BalancedVarietyPackCode.Cards;


[Pool(typeof(CurseCardPool))]
public class Despair() : CustomCardModel(
    baseCost: -1, CardType.Curse, CardRarity.Curse, TargetType.RandomEnemy)
{
    // should not be generated by "gain random curse" effects
    public override bool CanBeGeneratedByModifiers => false;
    public override bool HasTurnEndInHandEffect => true;
    public override int MaxUpgradeLevel => 0;
    
    
    public override IEnumerable<CardKeyword> CanonicalKeywords =>
        [ CardKeyword.Unplayable, CardKeyword.Eternal ];
    
    protected override IEnumerable<IHoverTip> ExtraHoverTips =>
        [ HoverTipFactory.FromPower<ThornsPower>() ];
    
    protected override IEnumerable<DynamicVar> CanonicalVars => 
        [ new PowerVar<ThornsPower>(5) ];
    
    
    protected override async Task OnTurnEndInHand(PlayerChoiceContext choiceContext)
    {
        if (CombatState is null || RunState is null) return;
        
        // select random enemy if possible
        IReadOnlyList<Creature> enemies = CombatState.Enemies;
        Creature? target = RunState.Rng.CombatTargets.NextItem(enemies);
        if (target is null) return;
        
        // apply Thorns to selected enemy
        await PowerCmd.Apply<ThornsPower>(
            choiceContext,
            [target],
            DynamicVars["ThornsPower"].BaseValue,
            applier: null,
            cardSource: this);
    }
}
